# Generated by Django 4.2.8 on 2023-12-09 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova_global', '0002_partners_services_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Görsel', 'verbose_name_plural': 'Görseller'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Partner', 'verbose_name_plural': 'Partnerler'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Proje', 'verbose_name_plural': 'Projeler'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Hizmet', 'verbose_name_plural': 'Hizmetler'},
        ),
    ]
